[Rainmeter]
Update=32
AccurateText=1
DynamicWindowSize=1

[Metadata]
Name=ClockBinarySkin
Author=Spl3ndOrS
Information=ASCII 5x5 clock binary flooding.
Version=1.1

[Variables]
; --- Essential Logic ---
Use12Hour=1
EnableRainbow=0
RainbowSpeed=0.003
EnableFlood=1

; --- Animation Speeds (Lower = Faster) ---
; 15 is exactly 0.5s On / 0.5s Off
BlinkSpeed=14
; 1 is instant, 10 is a slow flow
FloodSpeed=5

; --- Colon Customization ---
BlinkColon=1
UseDoubleColon=0
; Character used for the colon dots
CustomColonChar=:
; Space around the colon (0, 1, or 2)
ColonSpacing=0

; --- ASCII Character Mode ---
; Set to 1 to replace numbers with CustomChar
UseCustomChar=0
CustomChar=X

; --- Visuals (MUST BE MONOSPACED FONT ONLY) ---
FontFace=Consolas
FontSize=20
FontStyle=Bold
FontColor=0,255,150

; --- Background ---
; 1 = Visible, 0 = Invisible
ShowBackground=0
BGColor=10,10,10,220

; --- Layout ---
PaddingLeftRight=40
PaddingTopBottom=30
; Spacing between regular numbers
CharSpacing=2

[MeasureLuaScript]
Measure=Script
ScriptFile=Clock.lua

[MeterASCIIClock]
Meter=String
MeasureName=MeasureLuaScript
FontFace=#FontFace#
FontSize=#FontSize#
StringStyle=#FontStyle#
AntiAlias=1
SolidColor=#BGColor#
Padding=#PaddingLeftRight#,#PaddingTopBottom#,#PaddingLeftRight#,#PaddingTopBottom#
Text=%1
DynamicVariables=1
LeftMouseUpAction=[!SetVariable Use12Hour "(1-#Use12Hour#)"][!WriteKeyValue Variables Use12Hour "(1-#Use12Hour#)"][!UpdateMeasure MeasureLuaScript][!Redraw]

[ConditionShowBG]
Measure=Calc
Formula=#ShowBackground#
IfCondition=#ShowBackground# = 0
IfTrueAction=[!SetOption MeterASCIIClock SolidColor "0,0,0,1"]
IfFalseAction=[!SetOption MeterASCIIClock SolidColor "#BGColor#"]
OnUpdateAction=[!UpdateMeter MeterASCIIClock][!Redraw]
DynamicVariables=1
